- README.md
- evol/individual.py
- evol/population.py
- examples/example_annealing.py
- examples/example_pheromone.py
- tests/test_population.py
found a curious bug while in the train.
> population bug

- evol/individual.py
This pull request is mainly created for testing purposes
> Allow a fitness to be passed into an Individual on init.

- README.md
- REMINDERS.md
- docs/evol/evolution.m.html
- docs/evol/group.m.html
- docs/evol/helpers/combiners.m.html
- docs/evol/helpers/index.html
- docs/evol/helpers/pickers.m.html
- docs/evol/helpers/utils.m.html
- docs/evol/index.html
- docs/evol/individual.m.html
- docs/evol/population/base.m.html
- docs/evol/population/contest.m.html
- docs/evol/population/index.html
- docs/evol/population/island.m.html
- docs/evol/step.m.html
This is a first step for adding documentation.
> Pdoc documentation

- README.md
- docs/index.html
- evol/__init__.py
> Proper introduction docs

- .travis.yml
- setup.py
This refers to [this](https://github.com/godatadriven/evol/issues/18) issue.
> pytest is installed in build, not setup.py

- README.md
- REMINDERS.md
- docs/evolution.m.html
- docs/helpers/index.html
- docs/index.html
- docs/individual.m.html
- docs/population.m.html
- evol/__init__.py
- evol/evolution.py
- evol/helpers/__init__.py
- evol/individual.py
- evol/population.py
readme now contains a small introduction to the "why" of the library with a clear pointer to the examples folder for those who'd like to get started.
> much better readme

- setup.py
Setup hadn't been updated when we moved the repo
> Repo has moved. PEP8

- evol/evolution.py
- examples/example_rock_paper_scissors.py
- examples/number_of_parents.py
- examples/very_basic_tsp.py
- tests/test_evolution.py
> Remove Evolution.evolve and associated tests

- setup.py
seems that we can add `tests_require` to setup.py. seems nice enough to add.
> tests_require added to setup

- evol/population.py
- examples/number_of_parents.py
- tests/test_population.py
This replaces the min_individual and max_individual properties.
WIP: still requires more testing, especially `documented_best`.
> Implement current_best and documented_best

- README.md
> student mentioned a slight typo

- REMINDERS.md
- evol/evolution.py
- evol/logger.py
- evol/population.py
- evol/step.py
- examples/simple_logging.py
- tests/test_logging.py
this feature request has multiple logging fixes, mainly this PR fixes these two issues: https://github.com/godatadriven/evol/issues/53 and https://github.com/godatadriven/evol/issues/49. 
i rewrote/added a lot of tests because lots of weird things were happening. i also ensure two populations could log to the same log.
> every feature logging

- evol/population.py
Initially I only wanted to change the docstring but I ended up allowing the evaluate method to be passed in extra parameters. I figured that maybe in your evolution chain you'd like some `.evaluation()`-calls to be based on a few rounds while others are based on a lot. You can now pass `contests_per_round` and `individuals_per_contest` to each call. 
What do you think @rogiervandergeer good idea/bad idea? If you like it, does it require tests?
> better docstring and extra features

- docs/evolution.m.html
- docs/helpers/combiners/generic.m.html
- docs/helpers/combiners/index.html
- docs/helpers/combiners/permutation.m.html
- docs/helpers/index.html
- docs/helpers/mutators/index.html
- docs/helpers/mutators/permutation.m.html
- docs/helpers/utils.m.html
- docs/index.html
- docs/individual.m.html
- docs/logger.m.html
- docs/population.m.html
- docs/serialization.m.html
- docs/step.m.html
- setup.py
Just pushed to pypi, but the setup.py needs to be reflected in master. Also updated the docs.
> setup v0.2 as well as docs

- evol/population.py
- tests/test_population.py
Standardize arguments and make sure docstrings are correct.
Please do not delete this branch after merging; then we can keep working on this.
> Fix arguments

- .gitignore
- evol/__init__.py
- setup.py
@rogiervandergeer this is a super small change (to the extend that it is embarrassing to even make a pull request for), but this should make the front page of PyPi just that extra bit nicer.
> small improvement for pypi

- .travis.yml
> Also test on python 3.7

- .travis.yml
- examples/number_of_parents.py
- examples/rock_paper_scissors.py
- examples/simple_logging.py
- examples/simple_nonlinear.py
- examples/very_basic_tsp.py
Just flake8 the entire project :-) Less curly lines in IDEA
Cheers!
> Moar Flake8

- evol/evolution.py
- evol/helpers/_utils.py
- evol/helpers/combiners/_utils.py
- evol/helpers/combiners/generic.py
- evol/helpers/mutators/permutation.py
- evol/helpers/pickers.py
- evol/helpers/utils.py
- evol/individual.py
- evol/logger.py
- evol/population.py
- evol/serialization.py
- setup.py
> Upgrade flake8

- .travis.yml
- evol/individual.py
- evol/population.py
- examples/number_of_parents.py
- examples/rock_paper_scissors.py
- examples/simple_callback.py
- examples/simple_logging.py
- examples/simple_nonlinear.py
- examples/very_basic_tsp.py
- setup.py
- tests/conftest.py
- tests/test_examples.py
- tests/test_population.py
> Set examples to use multiple workers

- evol/population.py
I've fixed some typing issues that we were having in `population.py`.
> Fix typing issues

- evol/__init__.py
version upgrade for the pypi error
> changes in version number

- README.md
https://github.com/godatadriven/evol/issues/118
> add download stats to readme

- evol/evolution.py
- evol/population.py
- evol/step.py
Did some much-needed maintenance:
- Removed steps that couldn't be used anymore
- Removed the apply method that was a duplicate of the callback
- Fixed the type annotations of the steps.
> Clean up the EvolutionSteps

- evol/exceptions.py
- evol/helpers/groups.py
- evol/logger.py
> Create PopulationIsNotEvaluatedException and use is_evaluated property

- evol/__init__.py
Version bump required by pypi.
> Version 0.5.2: Elitism
